### ISSUE TITLE
Does this work with Traefik?

### ISSUE THREAD

**Issue by Spass1966** [thetarkus/docker-funkwhale#27]
I set NESTED_PROXY=1 but am receiving a Secure Connection Failed when connecting to https://funkwhale.hansen.agency/

**Comment by Spass1966** [comment]
docker-compose.yaml
```
 funkwhale:
    image: thetarkus/funkwhale
    container_name: funkwhale
    environment: 
      - FUNKWHALE_HOSTNAME=funkwhale.${DOMAIN}
      - NESTED_PROXY=1
      - FUNKWHALE_PROTOCOL=https
    volumes:
      - ./funkwhale/config:/data
      - ../music:/music:ro
    ports:
      - 3030:80
    labels:
      traefik.enable: "true"
      traefik.port: "3030"
      traefik.frontend.rule: "Host:funkwhale.${DOMAIN}"
    restart: always
```
`env` inside container:
```
DATABASE_URL=postgresql://funkwhale@:5432/funkwhale
FUNKWHALE_HOSTNAME=funkwhale.hansen.agency
HOSTNAME=a937dc17eacf
SHLVL=1
HOME=/root
MEDIA_ROOT=/data/media
TERM=xterm
FUNKWHALE_SPA_HTML_ROOT=/app/front/dist/index.html
STATIC_ROOT=/app/api/staticfiles
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DJANGO_SECRET_KEY=funkwhale
DJANGO_ALLOWED_HOSTS=127.0.0.1,*
FUNKWHALE_PROTOCOL=https
DJANGO_SETTINGS_MODULE=config.settings.production
NESTED_PROXY=1
MUSIC_DIRECTORY_PATH=/music
PWD=/
NGINX_MAX_BODY_SIZE=100M
```

Funkwhale is connectable via localhost but not through its Traefik assigned domain name. Help?
