### ISSUE TITLE
Is it possible to use plugins via environment?

### ISSUE THREAD

**Issue by ncoschrdr** [thetarkus/docker-funkwhale#54]
Hi, I'm currently trying to get the Scrobbler Plugin to work by trying to replicate the last answer with the Docker-compose command "environment" from [here](https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/497): 

```
"Actually, this is implemented! I forgot to close this issue, but thanks to our new plugin system, it's now possible to have scrobbling:
1. Add `FUNKWHALE_PLUGINS=funkwhale_api.contrib.scrobbler` to your .env file
1. In the UI, go to `/settings` then `manage plugins`, and configure the scrobbler plugin for your user :)"
```

I've added "FUNKWHALE_PLUGINS=funkwhale_api.contrib.scrobbler" to my compose file, but it doesn't seem to work, I hoped this would work because I tried adding "NGINX_MAX_BODY_SIZE=200M" by chance, and it worked.

Is this even possible?

Thanks in advance!

EDIT: my full compose file

```
version: '3.3'
services:
    funkwhale:
        container_name: funkwhale
        network_mode: traefik_default
        environment:
            - FUNKWHALE_HOSTNAME=192.168.0.150
            - NESTED_PROXY=0
            - FUNKWHALE_PLUGINS=funkwhale_api.contrib.scrobbler
            - NGINX_MAX_BODY_SIZE=200M
        volumes:
            - '/mnt/share/music_new/funkwhale_data:/data'
            - '/mnt/share/music_new/bought:/music:ro'
#        ports:
#            - '3030:80'
        image: thetarkus/funkwhale
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.funkwhale.entrypoints=http"
            - "traefik.http.routers.funkwhale.rule=Host(`funkwhale.mydomain.net`)"
            - "traefik.http.middlewares.funkwhale-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.funkwhale.middlewares=funkwhale-https-redirect"
            - "traefik.http.routers.funkwhale-secure.entrypoints=https"
            - "traefik.http.routers.funkwhale-secure.rule=Host(`funkwhale.mydomain.net`)"
            - "traefik.http.routers.funkwhale-secure.tls=true"
            - "traefik.http.routers.funkwhale-secure.tls.certresolver=http"
            - "traefik.http.routers.funkwhale-secure.service=funkwhale"
            - "traefik.http.services.funkwhale.loadbalancer.server.port=80"
            - com.centurylinklabs.watchtower.enable="true"
```
